regois/urls.py
from django.contrib import admin
from django.urls import path
from clinic import views
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from dal import autocomplete

from clinic.models import Diagnosis

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'^select2/', include('django_select2.urls')),
    path("", views.PtList.as_view(),name="pt-list"),
    path("diagnoo-auoto/", views.DigAutocomplete.as_view(create_field="namee"),name="diagnoo-auoto"),
    path('upload/',views.upload,name="upload"),
    path('list/',views.record_list,name="list"),
    path('delete/<int:pk>/',views.delete,name="delete"),
    path('ocr/<int:pk>',views.ocr,name="ocr"),
    path('view/<int:pk>/' , views.view , name="view"),
    path('download/<int:pk>/' , views.download , name="download"),
    path('xray/' , views.xray , name="xray"),
    path('xray_list/',views.xray_list,name="xray_list"),
    path('xray_delete/<int:pk>/',views.xray_delete,name="xray_delete"),
    path("visit-ad/", views.VisCreate.as_view(),name="visit-ad"),
    path('visit/<int:patient_id>', views.PatientVisitCreate.as_view(),name="visit-auoto"),
    url(
    'test-autocomplete/$',
    autocomplete.Select2QuerySetView.as_view(
        model=Diagnosis,
        create_field='name',
    ),
    name='select2_one_to_one_autocomplete',
),
    path("bacup-ad/", views.Step2View.as_view(),name="back-ad"),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


from django.contrib import admin

admin.autodiscover()
admin.site.enable_nav_sidebar = False

clinic/models.py
#import keras
from django.db import models
from django.utils.safestring import mark_safe
from ckeditor.fields import RichTextFormField
from ckeditor_uploader.fields import RichTextUploadingField
from .choices import *
from jsignature.mixins import JSignatureFieldsMixin

import tensorflow as tf
import numpy as np

#import keras
#from keras import backend as K
#from keras.layers.core import Dense, Dropout
#from keras.optimizers import Adam
#from keras.preprocessing.image import ImageDataGenerator
#from keras.models import Model
#from keras.callbacks import ReduceLROnPlateau, ModelCheckpoint
#from keras.models import Sequential, Model
#from keras.layers import Conv2D, MaxPooling2D, Dense, Dropout, Input, Flatten, SeparableConv2D
#from keras.layers import GlobalMaxPooling2D
#from keras.layers.normalization import BatchNormalization
#from keras.optimizers import Adam, SGD, RMSprop
from django.http import HttpResponse , HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render,redirect
from django.db import models
#from DOCTER.models import Docter
# import in-Built User Models
from django.contrib.auth.models import User


# Create your models here.
class Patient(models.Model):
    #drSchedule_date = models.DateField(null=True, blank=True)
    patient_id = models.AutoField(primary_key=True)
    patient_name = models.CharField(max_length=60, null=True, blank=True)
    #phone_number = CharField(max_length=60)
    email = models.EmailField()
    #def get_absolute_url(self):
        #return f"/visits/{self.pk}/"
    #drSchedule = models.OneToOneField(DrSchedule, on_delete=models.CASCADE, null=True, blank=True)
    #start = models.ForeignKey(TimeSlots, on_delete=models.CASCADE, null=True, verbose_name='Slot time')
    #paid = models.BooleanField(default=False)
    #skype_key = models.CharField(max_length=60, null=True, blank=True)

    def get_absolute_url(self):
        return reverse('visit-auoto', kwargs={'pk' : self.object.pk})


class Diagnosis(models.Model):

    name = models.CharField(max_length=20, default="Empty",primary_key=True)

    def __str__(self):
        return self.name
#import datetime






class PatientVisit(models.Model):


    patient = models.ForeignKey(Patient, null=True, on_delete=models.CASCADE)
    dermatologist= models.ForeignKey(User, null=True,related_name='doctorvisits', on_delete=models.CASCADE)
    lesion_site = models.CharField(max_length=200,choices=SITES)#add mark on image site save in db multiple point draw
    location_site_image = models.ImageField(upload_to='location_pics',default='default.jpg')
    lesion_number = models.IntegerField(default=1)
    lesion_size = models.CharField(max_length=200)
    Biopsy_Request = RichTextUploadingField(verbose_name="Biopsy Request")#how add template doc as template to fill it
    Diagnosis = models.ForeignKey(Diagnosis,on_delete=models.CASCADE)
    signature = models.BinaryField(null=True, blank=True)#didnt appear in html and save in db


    #def create_PatientVisit(sender, **kwargs):
        #if kwargs['created']:
            #patient = Patient.objects.create(patient=kwargs['instance'], pk=kwargs['instance'])

    #def get_absolute_url(self):
        #return reverse('visit-auoto', kwargs={'pk' : self.object.pk})




    class Meta:
        verbose_name_plural = "PatientVisit"

        #ordering = ('created',)

    def __unicode__(self):
        return u'%s' % self.pk






        #indexes = [models.Index(fields=["slug", "user"])]

    # Fields






# Create your models here.

    # def save(self, *args, **kwargs):
        # if not self.id:
        #     self.due_date = datetime.datetime.now()+ datetime.timedelta(days=15)
        # return super(Invoice, self).save(*args, **kwargs)






class LabTest(models.Model):

    title = models.TextField(null=False, blank=True)

class Specimen(models.Model):

    title = models.TextField(null=False, blank=True)






class LabRequest(models.Model):

    patient          = models.ForeignKey(Patient, on_delete=models.CASCADE, blank=True, null=True)
    test             = models.ForeignKey(LabTest, on_delete=models.CASCADE)
    accepted         = models.BooleanField(default=False)
    decline          = models.BooleanField(default=False)
    done             = models.BooleanField(default=False)
    created_by       = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    date_created     = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated          = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return str(self.patient.id)
    def get_absolute_url(self):
        return reverse('order-detail', args=[self.id])

class LabResult(models.Model):
    lab_request   = models.ForeignKey(LabRequest, on_delete=models.CASCADE, blank=True, null=True)
    result        = models.CharField(max_length=225)
    created_by    = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    date_created  = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated       = models.DateTimeField(auto_now_add=False, auto_now=True)
    def __str__(self):
        return str(self.lab_request)




class Medicine(models.Model):
    id=models.AutoField(primary_key=True)
    title = models.CharField(max_length=100,null=True, blank=True,)
    preparation = models.DecimalField(max_digits=5, decimal_places=2)
    manufacturer = models.CharField(max_length=100)
    genric = models.CharField(max_length=300)
    #image=models.FileField(max_length=255)
    form = models.CharField(max_length=300)
    conecentarion = models.CharField(max_length=300)
    #photo = models.ImageField(max_length=40,blank=True)

    def __str__(self):
        return self.title




class Prescriptions(models.Model):
    record = models.CharField(max_length=100)#check out about the unique field
    image = models.ImageField(upload_to='documents/',blank=False)
    username = models.ForeignKey(User,default=None,on_delete=models.PROTECT)
    text = models.TextField(default="")
    name = models.CharField(default="name",max_length=100)

    patientVisit = models.ForeignKey(PatientVisit,on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now=True)
    medicine = models.ManyToManyField(Medicine)#how select dropdown autocmplete medicine image thumbnail

    power =  models.PositiveIntegerField(max_length=100)
    route = models.CharField(max_length=1000)

    dosages_interval = models.PositiveIntegerField()
            #quantity = models.CharField(max_length=1000,choices=DOSE_FREQ_CHOICES)
    amount = models.CharField(max_length=1000,default=0)
    patient = models.ForeignKey(Patient,on_delete=models.CASCADE)
    def __str__(self):
        return self.record
    def delete(self , *args , **kwargs):
    	self.image.delete()
    	super().delete(*args,**kwargs)










# Create your models here.
#Model prescription.
class XRay(models.Model):
	image = models.ImageField(upload_to='xrays/',blank=False)
	username = models.ForeignKey(User,default=None,on_delete=models.PROTECT)
	name = models.CharField(default="name",max_length=100)
	predictions = models.TextField(default="")
	def __str__(self):
		return self.image.path

	def delete(self , *args , **kwargs):
		self.image.delete()
		super().delete(*args,**kwargs)




class XRayModel():

	def __init__(self , model_path):
		self.model_path = model_path

	def build_model(self):
		input_img = Input(shape=(224,224,3), name='ImageInput')
		x = Conv2D(64, (3,3), activation='relu', padding='same', name='Conv1_1')(input_img)
		x = Conv2D(64, (3,3), activation='relu', padding='same', name='Conv1_2')(x)
		x = MaxPooling2D((2,2), name='pool1')(x)

		x = SeparableConv2D(128, (3,3), activation='relu', padding='same', name='Conv2_1')(x)
		x = SeparableConv2D(128, (3,3), activation='relu', padding='same', name='Conv2_2')(x)
		x = MaxPooling2D((2,2), name='pool2')(x)

		x = SeparableConv2D(256, (3,3), activation='relu', padding='same', name='Conv3_1')(x)
		x = BatchNormalization(name='bn1')(x)
		x = SeparableConv2D(256, (3,3), activation='relu', padding='same', name='Conv3_2')(x)
		x = BatchNormalization(name='bn2')(x)
		x = SeparableConv2D(256, (3,3), activation='relu', padding='same', name='Conv3_3')(x)
		x = MaxPooling2D((2,2), name='pool3')(x)

		x = SeparableConv2D(512, (3,3), activation='relu', padding='same', name='Conv4_1')(x)
		x = BatchNormalization(name='bn3')(x)
		x = SeparableConv2D(512, (3,3), activation='relu', padding='same', name='Conv4_2')(x)
		x = BatchNormalization(name='bn4')(x)
		x = SeparableConv2D(512, (3,3), activation='relu', padding='same', name='Conv4_3')(x)
		x = MaxPooling2D((2,2), name='pool4')(x)

		x = Flatten(name='flatten')(x)
		x = Dense(1024, activation='relu', name='fc1')(x)
		x = Dropout(0.7, name='dropout1')(x)
		x = Dense(512, activation='relu', name='fc2')(x)
		x = Dropout(0.5, name='dropout2')(x)
		x = Dense(2, activation='softmax', name='fc3')(x)

		model = Model(inputs=input_img, outputs=x)
		return model

	def load_model(self , model_path=None):
		if model_path==None:
			model_path = self.model_path

		self.model = self.build_model()
		try:
			self.model.load_weights(model_path)
		except:
			print("Model weights not found")
		#TODO code for loading the model from .h5 file
class Invoice(models.Model):
    patient = models.ForeignKey(Patient, null=True, on_delete= models.SET_NULL)
    patient_email = models.EmailField(null=True, blank=True)
    billing_address = models.TextField(null=True, blank=True)
    date = models.DateField(null=True, blank=True)
    due_date = models.DateField(null=True, blank=True)
    message = models.TextField(default= "this is a default message.")
    vat = models.DecimalField(max_digits=9, decimal_places=2, blank=True, null=True)
    total_amount = models.DecimalField(max_digits=9, decimal_places=2, blank=True, null=True)

    status = models.BooleanField(default=False)
    def __str__(self):
        return str(self.patient)

clinic/templates/clinic/bs4_form.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
  {{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      {{ error }}
    {% endfor %}
  </div>
{% endif %}

{% for field in form.visible_fields %}
  <div class="form-group">
    {{ field.label_tag }}

    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class="form-control" %}
    {% endif %}

    {% if field.help_text %}
      <small class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}
  </div>
{% endfor %}

clinic/templates/clinic/database_backup.html
<form action="" method="post">



{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Save" />
</form>

clinic/templates/clinic/prescription_download.html
{% extends 'base.html' %}
{% block content %}
<div>
	<h2>Click on the link below to download</h2>
	<p><a class ="download" href="{{prescription.image.url}}" class="btn-large">Download {{prescription.image}}</a></p>
</div>
<br>
<br>
<div class="back">
	<form class="back_form" action="{% url 'prescription:view' prescription.pk  %}" method="post">
		{% csrf_token %}
		<input type="submit" class="btn-large" value="Go Back">
	</form>
</div>
{% endblock content %}

clinic/templates/clinic/prescription_ocr.html
{% extends 'base.html' %}
{% block content %}
<h1>Previous Records</h1>
<form method="POST" action="{% url 'prescription:ocr' prescriptions.pk %}">
	{% csrf_token %}
	<div class="prescriptions">
		{% if user.is_authenticated %}
		{%if request.user == prescriptions.username %}
		<div class="prescription">
			<h1><p>{{prescriptions.record}}</p></h1>
			<p>{{prescription.username}}</p>
			<div id="ocr_text">
				<textarea style="background-color: white;" id="textarea1" class="materialize-textarea" name="ocr-text">{{text}}</textarea>
			</div>	<!-- <p>{{prescriptions}}</p> -->
		</div>
		{% endif %}
		{% endif %}
	</div>
	<div>
		<input type="submit" class="btn-large" value="Submit"></input>
	</div>
</form>
<!-- <form method="POST" action="{url 'prescription:goback_delete' prescriptions.pk %}">
	<input type="submit" class="btn-large" value="Go Back">
</form> -->
<!-- </div> -->
<br>
<div class="back">
	<form class="back_form" action="{% url 'prescription:list'  %}" method="post">
		{% csrf_token %}
		<input type="submit" class="btn-large pulse" value="Go Back">
	</form>
</div>
{% endblock %}

clinic/templates/clinic/prescription_upload.html
{% load crispy_forms_tags %}
{% block content %}

<h1>Upload new Prescription</h1>
<div class="create-prescription">
	<div class="card hoverable">
		<div class="card-content">
			<form class="site-form" action="{% url 'upload' %}" method="post" enctype="multipart/form-data">
				{% csrf_token %}

				{{form|crispy}}
				<br>
				<br>
				<input type="submit" class="btn-large" value="Upload">
			</form>
		</div>
	</div>
</div>
<br>
<br>
<div class="back">
	<a href="{% url 'list'%}"><button class="btn btn-primary btn-large pulse">Go Back</button></a>
</div>


{% endblock %}

clinic/templates/clinic/prescription_view.html
{% extends 'base.html' %}
{% block content %}
	<i class="large material-icons" style="color:white">image</i>
	<br>
	<br>
	<div>
		<img class='image'src="{{prescription.image.url}}" style="padding:1px;border:thick solid red;" >
	</div>
	<br>
	<br>
	<div class="back">
		<a href="{% url 'download' prescription.pk %}"><button class="btn-large">Download</button></a>
		<a href="{% url 'list'%}"><button class=" btn-large ">Go Back</button></a>
	</div>
{% endblock %}

clinic/templates/clinic/prs_form.html
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>click here to backup database to local computer then you can restor</title>
  </head>


<form method="post" novalidate>
  {% csrf_token %}
{{ form.media}}
{{ form.as_p }}


  <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>

clinic/templates/clinic/pt_form.html
<form action="" method="post">



{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Save" />
</form>

clinic/templates/clinic/pt_list.html
{% load static %} {% block content %}
<p><a class="btn btn-default" >print all Listing</a></p>
<table class="table">
    <tr>
        <td>name</td>
        <td>email</td>
          <td>visit</td>

    </tr>
    {% for obj in object_list %}
    <tr>

        <td>{{ obj.patient_name }}</td>
        <td>{{ obj.email }}</td>

        <a href="/visits/{{patient.id}}">Link</a>
<td><small><a href="{% url 'visit-auoto' patient.id %}">Add Visit</a></small></td>



    </tr>
    {% endfor %}
    {% endblock %}

clinic/templates/clinic/sign.html
{% load static %}<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Signature Pad demo</title>
  <meta name="description" content="Signature Pad - HTML5 canvas based smooth signature drawing using variable width spline interpolation.">

  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">

  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">

  <link rel="stylesheet" href="css/signature-pad.css">

  <!--[if IE]>
    <link rel="stylesheet" type="text/css" href="css/ie9.css">
  <![endif]-->

  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-39365077-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
</head>
<body onselectstart="return false">
  <a id="github" style="position: absolute; top: 0; right: 0; border: 0" href="https://github.com/szimek/signature_pad">
      <img class="img-fluid rounded"   src="{% static 'skinlesion/body2.png' %}" height=100%" width="100%"/>
  </a>

  <div id="signature-pad" class="signature-pad">
    <div class="signature-pad--body">
      <canvas></canvas>
    </div>
    <div class="signature-pad--footer">
      <div class="description">Sign above</div>

      <div class="signature-pad--actions">
        <div>
          <button type="button" class="button clear" data-action="clear">Clear</button>
          <button type="button" class="button" data-action="change-color">Change color</button>
          <button type="button" class="button" data-action="undo">Undo</button>

        </div>
        <div>
          <button type="button" class="button save" data-action="save-png">Save as PNG</button>
          <button type="button" class="button save" data-action="save-jpg">Save as JPG</button>
          <button type="button" class="button save" data-action="save-svg">Save as SVG</button>
        </div>
      </div>
    </div>
  </div>

  <script src="js/signature_pad.umd.js"></script>
  <script src="js/app.js"></script>
</body>
</html>

clinic/templates/clinic/visit_form.html
{% load static %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% load bootstrap %}

{% load crispy_forms_field %}


<head>





<link rel="stylesheet" href="//code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.3/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css">


  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <style>
   ul#id_imagelesion li{
    display: inline-block;
    }
  </style>
  <style>
   ul#id_lesion_site li{
    display: inline-block;
    }
  </style>
  <style media="screen">
    .new-select {
    display: inline-block;
  }
  </style>
    <style>
      .form-control {
        margin: .25px;
      }
      .inline {
        margin: 6px;
        color: #f33;
      }
      .clles {
        margin: 6px;
        color: #f33;
      }
    }
    .colls {
      margin: 6px;
      color: #f33;
    }
      .tinymce{

      content: "Reference ";
  }

     .vital{
     height:90px;
     text-align: right;
  }
     .exam{
     height:90px;
     text-align: left;
  }
    .dd{
    height:90px;
    text-align: left;
  }
    .dist{
    height:90px;



    .select2-selection__rendered{
    height:3.4375rem;

  }

    #display {
      background-color: white;
      align: center;
      border-radius: 4px;
      padding-right: 10px;
    }
    #basic {
      background-color: maroon;
      text-align: center;
      border-radius: 4px;
      padding-right: 10px;
      float: left;
    }
    #shape {
      background-color: #DB9A2B;
      text-align: center;
      border-radius: 4px;
      padding-right: 10px;
    }
    #margin {
      background-color: #E9CE60;
      text-align: center;
      border-radius: 4px;
      padding-right: 10px;
      float: left;
    }

      #color {
        background-color: #4E842F;
        text-align: center;
        border-radius: 4px;
        padding-right: 10px;
        float: left;
      }
      .colorr {
      display: inline-block;
    }

    </style>
    <style>
      .bodyp {
        width: 300px;
        height: 300px;
        position: absolute;
        right:0;
        top:0;

    }
    </style>

</head>

{% block content %}


<div>
  <form method="post" novalidate>
    {% csrf_token %}
  {{ form.media}}


    {% include 'clinic/bs4_form.html' with form=form %}
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
  {% include 'clinic/sign.html' with form=form %}



   <div  id="imagelesion" >

                                   <input type="radio" name="one" label = "Choose One"  />
                                   <div class="new-select">

                                     <li class="new-select">
                                       <label tabindex="-1">
                                           <img src="{% static 'skinlesion/head.jpg' %}"   width="70" height="70" alt="">{{ form.lesion_site.0}}
                                       </label>
                                       </li>
                                       <li class="new-select">
                                       <label tabindex="-2">
                                           <img src="{% static 'skinlesion/papp.jpg' %}"   width="70" height="70" alt="">{{ form.lesion_site.1 }}
                                       </label>
                                       </li>
                                   <li class="new-select">
                                     <label tabindex="-3">
                                         <img src="{% static 'skinlesion/patch.jpg' %}"   width="70" height="70" alt="">{{ form.lesion_site.2 }}
                                     </label>
                                 </li>
                                <li class="new-select">
                                   <label tabindex="-4">
                                       <img src="{% static 'skinlesion/plauqe.jpg' %}"   width="70" height="70" alt="">{{ form.lesion_site.3 }}
                                   </label>
                          </li>
                      <li class="new-select">
                                 <label tabindex="-5">
                                     <img src="{% static 'skinlesion/nod.jpg' %}"   width="70" height="70" alt="">{{ form.lesion_site.4 }}
                                 </label>
                      </li>
                     <li class="new-select">
                               <label tabindex="-6">
                                   <img src="{% static 'skinlesion/pustule.jpg' %}"   width="70" height="70" alt="">{{ form.lesion_site.5 }}
                               </label>
                      </li>
                    <li class="new-select">
                             <label tabindex="-7">
                                 <img src="{% static 'skinlesion/vesicle.jpg' %}"   width="70" height="70" alt="">{{ form.lesion_site.6 }}
                             </label>
                           </li>
                           <label tabindex="-8">
                               <img src="{% static 'skinlesion/comdon.jpg' %}"   width="70" height="70" alt="">{{ form.lesion_site.7 }}
                           </label>

                         <label tabindex="-9">
                             <img src="{% static 'skinlesion/wheal.jpg' %}"   width="70" height="70" alt="">{{ form.lesion_site.8 }}
                         </label>

                       <label tabindex="-10">
                           <img src="{% static 'skinlesion/bur.jpg' %}"   width="70" height="70" alt="">{{ form.lesion_site.9 }}
                       </label>



</div>



<div class="">
  {% if location_image.image %}
 <img src="{{location_image.image.url }}">
 {% else %}
 <img src="{% static 'img/default.jpg' %}">
 {% endif %}
</div>


  </div>nammmmm

site_image_mark on it

  <div  id="bodypic" class="bodyp">
                      <img class="img-fluid rounded"   src="{% static 'skinlesion/body2.png' %}" height="600%" width="600%"/>
                      <p>site number choose</p> <!--for testing-->
                  </div>




   <!-- TABLE CONTENT SUPPRESSED FOR BREVITY'S SAKE -->


 <!-- THE MODAL WE WILL BE USING -->




{% endblock content %}

{% block js %}





<script type="text/javascript">
CKEDITOR.addCss(".cke_editable{cursor:text; font-size: 22px; font-family: Arial, sans-serif;}");
</script>




    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>  <!-- JQUERY HERE -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/modal.js' %}"></script>




{% endblock js %}

clinic/templates/clinic/xray_upload.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
	{% if user.is_authenticated %}
		<div class="card hoverable">
			<div class="card-content">
				<h1 style="color:black;">Upload X-Ray</h1>
				<div class="create-prescription">
					<form class="site-form" action="{% url 'xray' %}" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% if user.is_patient %}
						<p>Enter the Doctor Name In the last field</p>
						{% else %}
						<p>Enter the Patient Name In the last field</p>
						{% endif %}
						{{form|crispy}}
						<input type="submit" class="btn-large" value="Upload XRay">
					</form>
				</div>
				<br>
				<div class="back">
					<form class="back_form" action="{% url 'xray_list'  %}" method="post">
						{% csrf_token %}
						<input type="submit" class="btn-large" value="Go Back">
					</form>
				</div>
			</div>
		</div>

	{% endif %}
{% endblock %}